### ISSUE TITLE
having error when setup ZOU!!

### ISSUE THREAD

**Issue by tws0002** [cgwire/zou#116]
hi, I have an issue when Prepare database!! im using ubuntu to do the zou setup.
here is the error 
```
(zouenv) root@splinux:/opt/zou# DB_PASSWORD=password zou init_db
Creating database and tables...
Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 11, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/cli.py", line 30, in init_db
    flask_migrate.upgrade(directory=directory)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/util/compat.py", line 82, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/env.py", line 106, in <module>
    run_migrations_online()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/env.py", line 75, in run_migrations_online
    poolclass=pool.NullPool)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 460, in engine_from_config
    return create_engine(url, **options)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 584, in dbapi
    import psycopg2
  File "/opt/zou/zouenv/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /opt/zou/zouenv/lib/python3.6/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

```
hope you can help
Desmond

**Comment by frankrousseau** [comment]
Can you tell us which version of Ubuntu do you use?

**Comment by frankrousseau** [comment]
It seems to be related to the psycopg version: https://github.com/taigaio/taiga-back/issues/1122

**Comment by frankrousseau** [comment]
I will upgrade it soon.

**Comment by tws0002** [comment]
Hey i using Ubuntu 18.04

**Comment by tws0002** [comment]
hi,

is there any way I can fix this problem to make zou running? 
because planning to use for an upcoming project. so need a little time to give my team a test on it.

Thanks 
Desmond

**Comment by tws0002** [comment]
hey, guys how can I fix this?
![kitsu_error](https://user-images.githubusercontent.com/7018625/49152185-05caac80-f34d-11e8-8ebb-d9824443deb2.JPG)

**Comment by tws0002** [comment]
hey, guys I just solve the problem. all run smoothly now. I will close this.

Thanks 
Desmond

**Comment by DasPriester** [comment]
> hey, guys how can I fix this?
> ![kitsu_error](https://user-images.githubusercontent.com/7018625/49152185-05caac80-f34d-11e8-8ebb-d9824443deb2.JPG)

I have the same prompt! How exactly did you fix this?

**Comment by frankrousseau** [comment]
It just means that Zou is not running. See this section for help: https://zou.cg-wire.com/troubleshooting/

**Comment by DasPriester** [comment]
> It just means that Zou is not running. Have a look at this section for help: https://zou.cg-wire.com/troubleshooting/

I've done that already... But I cant find any solution there

**Comment by frankrousseau** [comment]
The thing is that you don't give enough information. You are just saying "it doesn't work" while it's running properly on dozens of installation. So, if you want help you have to tell us more about your setup and the error messages you get (especially the ones in `/opt/zou/gunicorn_error.log`)

**Comment by DasPriester** [comment]
Oh. Sorry.
I seem to be unable to run the init_data command.
I get the following error: "psycopg2.errors.UndefinedTable: relation "project_status" does not exist"

**Comment by frankrousseau** [comment]
Do you use the right environment variable? Did you run `DB_PASSWORD=yourdbpassword zou upgrade_db`?

**Comment by DasPriester** [comment]
Yes... I've tried with and without, but init does not want to run properly. I still egt the error from above about project_status not existing

**Comment by frankrousseau** [comment]
It means that your database is not properly configured. Please run the installation again from scratch on an Ubuntu distribution and make sure that you don't have any error message while setting up the database.

**Comment by nekrasovdmitriy** [comment]
Debian 12, same error

```
(zouenv) root@kitsu:/opt/zou# DB_PASSWORD=************ /opt/zou/zouenv/bin/zou init-db
Creating database and tables...
Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/zou/cli.py", line 46, in init_db
    flask_migrate.upgrade(directory=migrations_path)
  File "/opt/zou/zouenv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.11/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/zou/zouenv/lib/python3.11/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/opt/zou/zouenv/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/zou/zouenv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/zou/zouenv/lib/python3.11/site-packages/zou/migrations/env.py", line 108, in <module>
    run_migrations_online()
  File "/opt/zou/zouenv/lib/python3.11/site-packages/zou/migrations/env.py", line 74, in run_migrations_online
    connection = engine.connect()
                 ^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3276, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 308, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 914, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/event/attr.py", line 483, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/event/attr.py", line 497, in __call__
    fn(*args, **kw)
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 1912, in go
    return once_fn(*arg, **kw)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 749, in first_connect
    dialect.initialize(c)
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 386, in initialize
    super().initialize(connection)
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3115, in initialize
    super().initialize(connection)
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 518, in initialize
    self.server_version_info = self._get_server_version_info(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zou/zouenv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3384, in _get_server_version_info
    m = re.match(
        ^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 166, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
```
