### ISSUE TITLE
LDAP Sync broken

### ISSUE THREAD

**Issue by mathbou** [cgwire/zou#134]
**Issue:**

I tried to update Zou to 0.9.13 but the LDAP synchronization failed and corrupts a user mail with '[]'. The LDAP_EXCLUDED_ACCOUNTS key seems to also be malfunctionning, the user "Invité" should not be processed.
 However, the 0.9.10 works correctly, except the EMAIL_DOMAIN which has no effects.

<details>
  <summary><b>Traceback:</b></summary>

```python

[Synchro LDAP]
/opt/zou/env/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
User Invité updated.
Traceback (most recent call last):
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "person_email_key"
DETAIL:  Key (email)=([]) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou/env/bin/zou", line 10, in <module>
    sys.exit(cli())
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/zou/env/lib/python3.5/site-packages/zou/cli.py", line 153, in sync_with_ldap_server
    commands.sync_with_ldap_server()
  File "/opt/zou/env/lib/python3.5/site-packages/zou/app/utils/commands.py", line 242, in sync_with_ldap_server
    update_person_list_with_ldap_users(ldap_users)
  File "/opt/zou/env/lib/python3.5/site-packages/zou/app/utils/commands.py", line 211, in update_person_list_with_ldap_users
    "last_name": last_name
  File "/opt/zou/env/lib/python3.5/site-packages/zou/app/services/persons_service.py", line 190, in update_person
    person.update(data)
  File "/opt/zou/env/lib/python3.5/site-packages/zou/app/models/base.py", line 148, in update
    db.session.commit()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 937, in commit
    self.transaction.commit()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2237, in flush
    self._flush(objects)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2363, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2327, in _flush
    flush_context.execute()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "person_email_key"
DETAIL:  Key (email)=([]) already exists.
 [SQL: 'UPDATE person SET updated_at=%(updated_at)s, email=%(email)s WHERE person.id = %(person_id)s'] [parameters: {'updated_at': datetime.datetime(2019, 2, 21, 16, 22, 25, 625325), 'email': '[]', 'person_id': UUID('d1a5dd44-1aa3-4ad9-b042-4afde87f6a41')}] (Background on this error at: http://sqlalche.me/e/gkpj)

```

</details>

**Comment by frankrousseau** [comment]
Hello @mathbou, 
Thank you for reporting. We'll fix that next week.

**Comment by mathbou** [comment]
I just tried the Zou update but the sync problem is still there, it throw the same error when it tries to  update the user mail :/ However the EMAIL_DOMAIN and the LDAP_EXCLUDED_ACCOUNTS works pretty well know.

<details>
  <summary><b>Traceback:</b></summary>

```python

/opt/zou/env/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
User alexandre updated.
Traceback (most recent call last):
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "person_email_key"
DETAIL:  Key (email)=([]) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou/env/bin/zou", line 10, in <module>
    sys.exit(cli())
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/zou/env/lib/python3.5/site-packages/zou/cli.py", line 153, in sync_with_ldap_server
    commands.sync_with_ldap_server()
  File "/opt/zou/env/lib/python3.5/site-packages/zou/app/utils/commands.py", line 245, in sync_with_ldap_server
    update_person_list_with_ldap_users(ldap_users)
  File "/opt/zou/env/lib/python3.5/site-packages/zou/app/utils/commands.py", line 214, in update_person_list_with_ldap_users
    "last_name": last_name
  File "/opt/zou/env/lib/python3.5/site-packages/zou/app/services/persons_service.py", line 190, in update_person
    person.update(data)
  File "/opt/zou/env/lib/python3.5/site-packages/zou/app/models/base.py", line 155, in update
    db.session.commit()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 937, in commit
    self.transaction.commit()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2237, in flush
    self._flush(objects)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2363, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2327, in _flush
    flush_context.execute()
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/opt/zou/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "person_email_key"
DETAIL:  Key (email)=([]) already exists.
 [SQL: 'UPDATE person SET updated_at=%(updated_at)s, email=%(email)s WHERE person.id = %(person_id)s'] [parameters: {'updated_at': datetime.datetime(2019, 2, 27, 18, 10, 46, 15467), 'person_id': UUID('a580b688-be7e-4fad-9efd-c2a97993ec47'), 'email': '[]'}] (Background on this error at: http://sqlalche.me/e/gkpj)

```
</details>

**Comment by frankrousseau** [comment]
@mathbou Is it ok with the last update?

**Comment by mathbou** [comment]
It works like a charm 👍

**Comment by frankrousseau** [comment]
Awesome!
