### ISSUE TITLE
zou fails to start after upgrading to 0.9.33

### ISSUE THREAD

**Issue by cameronpd** [cgwire/zou#150]
Hi,

I just upgraded to zou 0.9.33 from 0.9.24 and zou now fails to start with the following in the error log, also trying to run the db upgrade command has a similar error.

I updated using pip as per the docs.

<details>
<summary>Error log output:</summary>

```python

Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/zou/zouenv/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/opt/zou/zouenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/zou/zouenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/zou/zouenv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/zou/zouenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/zou/zouenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/zou/zouenv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/zou/zouenv/lib/python3.7/site-packages/zou/app/__init__.py", line 119, in <module>
    load_api()
  File "/opt/zou/zouenv/lib/python3.7/site-packages/zou/app/__init__.py", line 114, in load_api
    from . import api
  File "/opt/zou/zouenv/lib/python3.7/site-packages/zou/app/api.py", line 17, in <module>
    from .blueprints.playlists import blueprint as playlists_blueprint
  File "/opt/zou/zouenv/lib/python3.7/site-packages/zou/app/blueprints/playlists/__init__.py", line 4, in <module>
    from .resources import (
  File "/opt/zou/zouenv/lib/python3.7/site-packages/zou/app/blueprints/playlists/resources.py", line 19, in <module>
    from zou.app.stores import queue_store
  File "/opt/zou/zouenv/lib/python3.7/site-packages/zou/app/stores/queue_store.py", line 4, in <module>
    from rq import Queue
  File "/opt/zou/zouenv/lib/python3.7/site-packages/rq/__init__.py", line 9, in <module>
    from .queue import get_failed_queue, Queue
  File "/opt/zou/zouenv/lib/python3.7/site-packages/rq/queue.py", line 61
    async=True, job_class=None):
        ^
SyntaxError: invalid syntax

```
</details>

<details>
<summary>A very big guess as to the problem</summary>
Based on my limited python ability, it appears to be pointing at async=True there at the end, I believe async is now a [reserved keyword in python 3.7](https://docs.python.org/3.7/whatsnew/3.7.html?highlight=reserved%20keywords).

Looking at the pip upgrade output, rq package is required to be 0.10.0, and a quick look in the rq pip release history shows that it doesn't support python 3.7 till 0.12.0 released in July last year.

Although having said that, everything was working fine in 0.9.24 and 0.9.21 before it, so I'm not sure if any of this is correct.
</details>

Running:
on Fedora 29
with Python 3.7.2

Thanks

**Comment by frankrousseau** [comment]
Hello @cameronpd,

Thank you for reporting this bug. Unfortunately, we do not support Fedora for free. But we will make some trials on Travis to see if something can be fixed.

**Comment by cameronpd** [comment]
Ok thanks,

But if it's only a matter of installing a different version of python, Fedora has packages for 3.4, 3.5, 3.6 3.7 and 3.8, as well as 2.6 and 2.7, it just defaults to installing 2.7 and 3.7. Your docs just say preferably 3, so I left it as default.

**Comment by frankrousseau** [comment]
Yep, we didn't know about this issue until you mentioned it. I'm still struggling with Travis configuration. But I don't spend much time on it because it wouldn't be fair towards our customer which have other needs (we give priority to their requests). When it's solved or if I have other questions, I will tell you.

**Comment by frankrousseau** [comment]
Problem reproduced: https://travis-ci.org/cgwire/zou/jobs/529726653

**Comment by frankrousseau** [comment]
Tests are now passing. We will publish probably a new release this weekend.

**Comment by frankrousseau** [comment]
The new version is published. @cameronpd can you tell me if it's working?

**Comment by cameronpd** [comment]
Great thanks!
Looks good, all seems to be working.

We just started running our first internal project through our new workflow of Kitsu/Zou and Avalon, so this is great timing.

Thanks again.

**Comment by frankrousseau** [comment]
Great! Could you tell us for which studio? I'm pretty sure that the Avalon guy would be glad to hear about it!

**Comment by cameronpd** [comment]
TeePee Studios, a small studio in Melbourne Australia.

We've had some contact with the Avalon guys on their Gitter chat, as Avalon isn't exactly easy to setup and get running, but I don't think any studio name have been mentioned.

**Comment by frankrousseau** [comment]
Great thank you!
