### ISSUE TITLE
CMYK images are not supported

### ISSUE THREAD

**Issue by mathbou** [cgwire/zou#161]
**Issue:**

The 'Attach Preview' function of Kitsu raise an error with cmyk images, but it seems to be a processing error within zou.

<details>
  <summary><b>Traceback:</b></summary>

```python

[2019-06-13 13:33:31,062] ERROR in __init__: Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 706, in _save,
    rawmode, mode = _OUTMODES[mode],
KeyError: 'CMYK',
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request,
    rv = self.dispatch_request(),
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request,
    return self.view_functions[rule.endpoint](**req.view_args),
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 477, in wrapper,
    resp = resource(*args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 84, in view,
    return self.dispatch_request(*args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request,
    resp = meth(*args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 38, in wrapper,
    return fn(*args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/zou/app/blueprints/previews/resources.py", line 162, in post,
    self.save_picture_preview(instance_id, uploaded_file),
  File "/usr/local/lib/python3.7/site-packages/zou/app/blueprints/previews/resources.py", line 220, in save_picture_preview,
    return self.save_variants(original_tmp_path, instance_id),
  File "/usr/local/lib/python3.7/site-packages/zou/app/blueprints/previews/resources.py", line 292, in save_variants,
    instance_id,
  File "/usr/local/lib/python3.7/site-packages/zou/app/utils/thumbnail.py", line 140, in generate_preview_variants,
    turn_into_thumbnail(picture_path, size),
  File "/usr/local/lib/python3.7/site-packages/zou/app/utils/thumbnail.py", line 76, in turn_into_thumbnail,
    im.save(file_path, "PNG"),
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 1728, in save,
    save_handler(self, fp, filename),
  File "/usr/local/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 708, in _save,
    raise IOError("cannot write mode %s as PNG" % mode),
OSError: cannot write mode CMYK as PNG,


```
</details>

**Comment by BigRoy** [comment]
Thanks for reporting with the traceback.

Zou saves the image as `.png` which does [not support CMYK](https://www.quora.com/Why-wont-Photoshop-save-a-CMYK-document-as-PNG).

Is it important for you that `zou` preserves the CMYK online? If so, it must resort to another format than PNG.

Otherwise I think the used image library PIL should allow conversion to RGB and then saving the resulting `.png`.

Would that last step work good for you? Or is there a reason you need CMYK uploaded?

**Comment by mathbou** [comment]
The conversion shoud be enough for our needs.

**Comment by BigRoy** [comment]
That's great. Unfortunately I'm not running a local `zou` so I can't test it here but I can set up a PR for you to test it if it helps. If you are not afraid to change some code locally and set up a PR you can do that too of course and ensure it's tested.

Basically, what needs to be done is to [do the conversion from CMYK to RGB](https://stackoverflow.com/questions/33101659/convert-from-cmyk-to-rgb/36981871#36981871), specifically:
```python
if im.mode == 'CMYK':
    im = im.convert('RGB')
```

The places where this should be done is prior to saving out to `.png`:

- https://github.com/cgwire/zou/blob/74b165abcc4c01b4ab84d221b8622b243afb164d/zou/app/utils/thumbnail.py#L76
- https://github.com/cgwire/zou/blob/74b165abcc4c01b4ab84d221b8622b243afb164d/zou/app/utils/thumbnail.py#L37

As such, you should be able to put it above those lines and it should allow you to correctly attach your preview.

Are you able to test this yourself and set up a PR?

**Comment by mathbou** [comment]
I'm using Zou through Docker so I cant set up a PR but I just tested the modification inside a fresh container and it works well.

**Comment by frankrousseau** [comment]
I will include this fix soon. Or feel free to submit a PR!

**Comment by frankrousseau** [comment]
And thank you both for solving this issue!

**Comment by frankrousseau** [comment]
It's included in the latest release. @mathbou Can you try again?

**Comment by mathbou** [comment]
It's working, thanks guys  😃
