### ISSUE TITLE
Error with gazu.project.update_project_data() in 0.10.26

### ISSUE THREAD

**Issue by Arubinu** [cgwire/zou#179]
Hello,

Since Zou version 0.10.26, an error is returned by Zou when using the `gazu.project.update_project_data()` method (works in 0.10.25).

Here is the error returned by Gazu:
```
Traceback (most recent call last):
  File "zou_setup.py", line 478, in save
    gazu.project.update_project_data( project, project_data )
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gazu/project.py", line 124, in update_project_data
    update_project(project)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gazu/project.py", line 104, in update_project
    return client.put("data/projects/%s" % project["id"], project)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gazu/client.py", line 176, in put
    check_status(response, path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gazu/client.py", line 247, in check_status
    raise ServerErrorException(path)
gazu.exception.ServerErrorException: data/projects/a842387e-5ed5-4ee3-89db-a4d5b28cc8d2
```

And here is the error present in '/opt/zou/logs/gunicorn_error.log':
```
[2019-09-13 11:58:06 +0200] [14199] [ERROR] Error handling request //data/projects/c630d973-9306-4d71-b04c-b7fa3c43bdf6
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.5/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
   return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/blueprints/crud/base.py", line 276, in put
    instance.update(data)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/models/base.py", line 190, in update
    setattr(self, key, value)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 268, in __set__
    instance_state(instance), instance_dict(instance), value, None
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 1310, in set
    new_values, old_collection, new_collection, initiator=evt
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/collections.py", line 798, in bulk_replace
    appender(member, _sa_initiator=initiator)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/collections.py", line 1113, in append
    item = __set(self, item, _sa_initiator)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/collections.py", line 1078, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/collections.py", line 715, in fire_append_event
    self.owner_state, self.owner_state.dict, item, initiator
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 1151, in fire_append_event
    value = fn(state, value, initiator or self._append_token)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 45, in append
    item_state = attributes.instance_state(item)
AttributeError: 'str' object has no attribute '_sa_instance_state'
```

**Comment by frankrousseau** [comment]
Thank you @Arubinu for the report!
