### ISSUE TITLE
Error uploading preview with comment

### ISSUE THREAD

**Issue by Tilix4** [cgwire/zou#212]
Ubuntu 18.04

`/opt/zou/logs/gunicorn_error.log`:
```
[2019-12-23 20:55:23 +0100] [21422] [INFO] Using worker: gevent
[2019-12-23 20:55:23 +0100] [21427] [INFO] Booting worker with pid: 21427
[2019-12-23 20:55:23 +0100] [21428] [INFO] Booting worker with pid: 21428
[2019-12-23 20:55:23 +0100] [21429] [INFO] Booting worker with pid: 21429
[2019-12-23 20:56:06,010] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/pictures/thumbnails/050/8db/0508db88-9971-4160-8718-90454140de57'
[2019-12-23 20:56:06,112] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/pictures/thumbnails/050/8db/0508db88-9971-4160-8718-90454140de57'
[2019-12-23 20:56:06,766] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/pictures/thumbnails/050/8db/0508db88-9971-4160-8718-90454140de57'
[2019-12-23 20:56:08,641] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/pictures/previews/0f8/99e/0f899ec0-40d3-460a-b4eb-47f715e5d69f'
[2019-12-23 20:56:08,652] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/movies/previews/0f8/99e/0f899ec0-40d3-460a-b4eb-47f715e5d69f'
[2019-12-23 20:56:08,739] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/pictures/previews/0f8/99e/0f899ec0-40d3-460a-b4eb-47f715e5d69f'
[2019-12-23 20:56:19,082] ERROR in __init__: Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/blueprints/previews/resources.py", line 185, in post
    self.save_picture_preview(instance_id, uploaded_file)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/blueprints/previews/resources.py", line 234, in save_picture_preview
    tmp_folder, instance_id, uploaded_file
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/app/utils/thumbnail.py", line 23, in save_file
    file_to_save.save(file_path)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2799, in save
    dst = open(dst, "wb")
PermissionError: [Errno 13] Permission denied: '/tmp/zou/203c3e40-5665-4b01-aea6-6676f59176ad.jpg'
```

**Comment by flablog** [comment]
By default the Zou user can't write in /tmp/zou (at least on ubuntu server)...  It should be clearer in the doc, but you can do a chown -r or chmod on that folder.

**Comment by Tilix4** [comment]
Yeah, I just managed to do it. Thanks for your quick reply! It must be written in the doc.

**Comment by flablog** [comment]
Be aware that this solution is temporary: after a reboot it will probably be unset.

You can change the temporary folder in the configuration with the TMP_DIR environment variable

**Comment by Tilix4** [comment]
Thank you very much!
