### ISSUE TITLE
Can't add tasks for shots

### ISSUE THREAD

**Issue by DuanXu-anim** [cgwire/zou#286]
![image](https://user-images.githubusercontent.com/48669854/96543139-4e3f3a80-12d6-11eb-8eba-9349fa7a8aac.png)
It's a bug or something else?

**Comment by DuanXu-anim** [comment]
<img width="317" alt="1" src="https://user-images.githubusercontent.com/48669854/96543729-9579fb00-12d7-11eb-9241-23fd8abfac9c.png">

**Comment by DuanXu-anim** [comment]
[2020-10-20 13:19:27,200] ERROR in __init__: Traceback (most recent call last):
  File "/data/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/data/zou/zouenv/lib/python3.6/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/data/zou/zouenv/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/data/zou/zouenv/lib/python3.6/site-packages/werkzeug/routing.py", line 1798, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

**Comment by DuanXu-anim** [comment]
I paste the error log about this issue.

**Comment by frankrousseau** [comment]
Hello @DuanXu-anim,

You need to update both frontend and backend. Make sure that your navigator cache is cleaned too (ctrl+F5).

**Comment by DuanXu-anim** [comment]
got it, thank you !
