### ISSUE TITLE
FFMPEG Normalization error

### ISSUE THREAD

**Issue by kmarcinowski** [cgwire/zou#291]
Hello,
I'm facing some issues while uploading video files mov / mp4 .h264 - file size is not an issue, tested 600KB and 20MB. 
I can not find where ffmpeg stderr is located - here's gunicorn_error.log I have after upload:
`[2020-11-04 05:01:36,445] ERROR in resources: ffmpeg error (see stderr output for detail)
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/blueprints/previews/resources.py", line 202, in post
    self.save_movie_preview(instance_id, uploaded_file)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/blueprints/previews/resources.py", line 259, in save_movie_preview
    uploaded_movie_path, fps=fps, width=width, height=height
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/utils/movie_utils.py", line 84, in normalize_movie
    stream.run(quiet=False, capture_stderr=True)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
[2020-11-04 05:01:36,446] ERROR in resources: Normalization failed.
[2020-11-04 05:04:14,444] ERROR in movie_utils: b"ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609\n  configuration: --prefix=/usr --extra-v$
[2020-11-04 05:04:14,445] ERROR in resources: ffmpeg error (see stderr output for detail)
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/blueprints/previews/resources.py", line 202, in post
    self.save_movie_preview(instance_id, uploaded_file)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/blueprints/previews/resources.py", line 259, in save_movie_preview
    uploaded_movie_path, fps=fps, width=width, height=height
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/utils/movie_utils.py", line 84, in normalize_movie
    stream.run(quiet=False, capture_stderr=True)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
[2020-11-04 05:04:14,445] ERROR in resources: Normalization failed.
`

I'd be glad if anyone could help me with that one!
Thanks in advace!

**Comment by kmarcinowski** [comment]
Figured that ffmpeg probably is wrong, updated and it's working great.

**Comment by frankrousseau** [comment]
Ok great. I had no idea about what was wrong.
