### ISSUE TITLE
event_handlers not working

### ISSUE THREAD

**Issue by Aderemi-Adesada** [cgwire/zou#295]
i havent been able to get my event handler to work. it crashes zou
it keeps throwing the error below
`[2020-11-16 12:09:19 +0100] [14752] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/__init__.py", line 129, in <module>
    load_api()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/__init__.py", line 123, in load_api
    api.configure(app)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/api.py", line 36, in configure
    load_plugins(app)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/api.py", line 90, in load_plugins
    load_plugin(app, plugin)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/api.py", line 115, in load_plugin
    for (route_path, resource) in plugin.routes
AttributeError: module 'event_handlers' has no attribute 'routes'`
pls how can i fix it

**Comment by frankrousseau** [comment]
Did you configure properly the `event_handlers` path?

**Comment by Aderemi-Adesada** [comment]
i used the default 
`/opt/zou/plugins`

**Comment by frankrousseau** [comment]
Try to not use the default value: https://zou.cg-wire.com/events/#define-a-location-for-your-event-handlers

**Comment by Aderemi-Adesada** [comment]
it is still not working
i created EVENT_HANDLERS_FOLDER variable
`Environment="EVENT_HANDLERS_FOLDER=/home/asuna/test"`
/home/asuna/test containers my event handler module which i named event_handlers

This is how my folder look like:

ls /home/asuna/test/event_handlers
__init__.py
asset_new.py

**Comment by frankrousseau** [comment]
Hello @Aderemi-Adesada did you manage to make it work?

**Comment by Aderemi-Adesada** [comment]
no, I am not sure what I was doing wrong. I am handling the events externally for now. thanks for the support 👍
