### ISSUE TITLE
RuntimeError occurred when running event

### ISSUE THREAD

**Issue by fananimi** [cgwire/zou#303]
Well, I just run the event server with the following commands:

```
$ DB_PASSWORD=postgres gunicorn --worker-class gevent -b 127.0.0.1:5001 -w 3 zou.event_stream:app
```

And then I run the frontend application. After the established connection between the frontend and backend, I found the following error.

```
[2021-01-07 18:08:54 +0700] [133652] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket&sid=bd26beaab79d47fd8b0b79793d650251
Traceback (most recent call last):
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/flask_socketio/__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/socketio/server.py", line 526, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/engineio/server.py", line 350, in handle_request
    packets = socket.handle_get_request(
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/engineio/socket.py", line 105, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/engineio/socket.py", line 146, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/fanani/Projects/dakon/zou/env/lib/python3.8/site-packages/engineio/async_drivers/gevent.py", line 35, in __call__
    raise RuntimeError('You need to use the gevent-websocket server. '
RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.
```

Here my local environment:

Python: 3.8.5
Nodejs: v14.15.4

**Comment by frankrousseau** [comment]
Hi @fananimi, you should use the following command line: 

```
gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b 127.0.0.1:5001 -w 1 zou.event_stream:app
```

**Comment by fananimi** [comment]
Thanks @frankrousseau , it's cool and running well now.
