### ISSUE TITLE
Cannot upgrade zou because "zou upgrade_db" crashes.

### ISSUE THREAD

**Issue by kguyaux** [cgwire/zou#356]
Helle everybody,
when trying to upgrade zou, the `zou upgrade_db`-command, results in an error:
```
$ zou upgrade_db
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 1cb44194db49 -> fb87feaaa094, add missing unique constraints
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: could not create unique index "entity_link_uc"
DETAIL:  Key (entity_in_id, entity_out_id)=(6c8b4762-6d63-42b4-939a-9833cc958a8e, 9d5f6723-2beb-450a-898a-e25bae58efb9) is duplicated.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/cli.py", line 76, in upgrade_db
    flask_migrate.upgrade(directory=directory)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/env.py", line 110, in <module>
    run_migrations_online()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/env.py", line 89, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
    step.migration_fn(**kw)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/versions/fb87feaaa094_add_missing_unique_constraints.py", line 22, in upgrade
    op.create_unique_constraint('entity_link_uc', 'entity_link', ['entity_in_id', 'entity_out_id'])
  File "<string>", line 8, in create_unique_constraint
  File "<string>", line 3, in create_unique_constraint
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/operations/ops.py", line 375, in create_unique_constraint
    return operations.invoke(op)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/operations/base.py", line 354, in invoke
    return fn(self, operation)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/operations/toimpl.py", line 155, in create_constraint
    operation.to_constraint(operations.migration_context)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/ddl/impl.py", line 263, in add_constraint
    self._exec(schema.AddConstraint(const))
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/ddl/impl.py", line 146, in _exec
    return conn.execute(construct, multiparams)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) could not create unique index "entity_link_uc"
DETAIL:  Key (entity_in_id, entity_out_id)=(6c8b4762-6d63-42b4-939a-9833cc958a8e, 9d5f6723-2beb-450a-898a-e25bae58efb9) is duplicated.

[SQL: ALTER TABLE entity_link ADD CONSTRAINT entity_link_uc UNIQUE (entity_in_id, entity_out_id)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```
Is there a possible fix for this?

**Comment by frankrousseau** [comment]
Try to run this script on your instance (assuming that Gazu has already log in your instance and that you retrieved a given project) :

```python                                                                                                                                                                                     
shots = gazu.shot.all_shots_for_project(project)                                    
for shot in shots:                                                              
    shot_id = shot["id"]                                                        
    links = gazu.client.fetch_all("entity-links?entity_in_id=%s" % shot_id)                             
                                                                                 
    link_map = {}                                                               
    for link in links:                                                          
         if not link["entity_out_id"] in link_map:                               
             link_map[link["entity_out_id"]] = 0                                 
             link_map[link["entity_out_id"]] += 1                                    

     for link in links:                                                          
          if link_map[link["entity_out_id"]] > 1:                                 
              link_map[link["entity_out_id"]] -= 1                                
              print("delete", link["id"])                                         
              gazu.client.delete("data/entity-links/%s" % link["id"])  
```

**Comment by frankrousseau** [comment]
Then run the upgrade command again

**Comment by kguyaux** [comment]
Thanks Frank!
Unfortunately I have to first work on my schedule to try the solution, but I would like to thank already :-)
I'll keep posted about the results(probably next wednesday)
