### ISSUE TITLE
Zou Upgrade crashes with routes error

### ISSUE THREAD

**Issue by ddesmond** [cgwire/zou#373]
Hey Frank!

im trying to update kitsu instance from 0.12.27 to latest, and this hapens:

`DB_PASSWORD=XXXXXXX zou upgrade_db
Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 5, in <module>
    from zou.cli import cli
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/cli.py", line 9, in <module>
    from zou.app.utils import dbhelpers, auth, commands
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/__init__.py", line 129, in <module>
    load_api()
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/__init__.py", line 123, in load_api
    api.configure(app)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/api.py", line 36, in configure
    load_plugins(app)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/api.py", line 90, in load_plugins
    load_plugin(app, plugin)
  File "/opt/zou/zouenv/lib/python3.5/site-packages/zou/app/api.py", line 115, in load_plugin
    for (route_path, resource) in plugin.routes
AttributeError: module 'event_handlers' has no attribute 'routes'`

Have updated kitsu to latest but this one still giving issues after a retry.
Kitsu is now down until I resolve this. Any tips?

**Comment by frankrousseau** [comment]
Hello @ddesmond, I think it's because there are a files in `event_handlers` folder. Can you try to add a `routes = []` variable into it?

**Comment by ddesmond** [comment]
Where should i add that? in the api.py?

**Comment by frankrousseau** [comment]
Can you try to remove the the folder or to add the variable `name = 'empty'`?

**Comment by ddesmond** [comment]
Removing event_handlers directory did the trick. It seems i can log back in. Thanks Frank!
ps. Kitsu us now on 0.13.6 ! woohoo
