### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by dzoniandric** [cgwire/zou#407]
Hi everyone, I am almost certain I am doing something wrong but not sure what and how should I configure zou.

When I attempt to make new user and send email request to them, I get an error. My gunicorn error log displays this:

```
[2022-01-15 19:48:12,954] ERROR in __init__: Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/zou/app/blueprints/persons/resources.py", line 297, in get
    persons_service.invite_person(person_id)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/zou/app/services/persons_service.py", line 359, in invite_person
    emails.send_email(subject, body, person.email, html=html)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/zou/app/utils/emails.py", line 21, in send_email
    mail.send(message)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/opt/zou/zouenv/lib/python3.9/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.9/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/opt/zou/zouenv/lib/python3.9/site-packages/gevent/socket.py", line 88, in create_connection
    addrs = list(getaddrinfo(host, port, 0, SOCK_STREAM))
  File "/opt/zou/zouenv/lib/python3.9/site-packages/gevent/_socketcommon.py", line 247, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/opt/zou/zouenv/lib/python3.9/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/gevent/threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
socket.gaierror: [Errno -2] Name or service not known
```

This is my /etc/systemd/system/zou.service config file:

```
[Unit]
Description=Gunicorn instance to serve the Zou API
After=network.target

[Service]
User=zou
Group=www-data
WorkingDirectory=/opt/zou
# Append DB_USERNAME=username DB_HOST=server when default values aren't used
# ffmpeg must be in PATH
Environment="DB_PASSWORD=password"
Environment="SECRET_KEY=OoCeevee0peiw1Hu"
Environment="PATH=/opt/zou/zouenv/bin:/usr/bin"
Environment="PREVIEW_FOLDER=/opt/zou/previews"
Environment="TMP_DIR=/opt/zou/tmp"
ExecStart=/opt/zou/zouenv/bin/gunicorn  -c /etc/zou/gunicorn.conf -b 127.0.0.1:5000 zou.app:app
Environment="MAIL_SERVER=smtppro.zoho.eu:587"
Environment="MAIL_USERNAME=myemail@mydomain.com"
Environment="MAIL_PASSWORD=mypassword"
Environment="MAIL_DEFAULT_SENDER=no-reply@mydomain.com"
Environment="MAIL_USE_TLS=True"

[Install]
WantedBy=multi-user.target
```

Thanks for any help. Great app and very good documentation, by the way. Installation was very clear and easy, except the configuration part.

**Comment by frankrousseau** [comment]
Did you set these variables properly?

```
Environment="MAIL_USERNAME=myemail@mydomain.com"
Environment="MAIL_PASSWORD=mypassword"
```
