### ISSUE TITLE
Problem with update to last master commits in Zou and Kitsu after switching from own dev branch!

### ISSUE THREAD

**Issue by Ramel** [cgwire/zou#414]
As working on my own Gitlab *mattermost* branch, when I switch back to Github **zou** *master* branch, as my patchs were applied, and before new release (cannot wait)  I have now an error while launching **zou** service.

After searching a while, I found a solution. I share it, as is, just in case. But I don't know if it's the best way to solve it.

Starting point:

 - **Zou** in myowned.gitlab.com@mattermost branch
 - **Kitsu** in myowned.gitlab.com@build-mattermost branch
 
```
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ DB_PASSWORD=<PWD> FLASK_APP=zou.app flask db history -d `python -c "import site; print(site.getsitepackages()[0])"`/zou/migrations

return:
3e0538ddf80f -> 7b1f765677d8 (head), add column chat_webhook_mattermost
…
```
That's my dev *mattermost* branch, which I've applied to my server instance. It's working well. But if I switch back to Cgwire repo, I face a problem, that's my **kistu** instance is then stuck.

First, stop **zou**

```
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ systemctl stop {zou,zou-events.service}
```

Then I upgrade **zou** to :

https://github.com/cgwire/zou.git@master

and **kitsu** to my own Gitlab where I've pushed a new npm build:

https://myowned.gitlab.com/kitsu.git@build-master

```
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ bin/pip3 install -U git+https://github.com/cgwire/zou.git
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ cd /opt/kitsu
# Switch to my new npm build based on https://github.com/cgwire/kitsu.git@master
# but hosted on https://myowned.gitlab.com/kitsu.git@build-master
# as there is no new release on github repo
(zouenv) zou@HOSTNAME:/opt/kitsu$ git checkout build-master
(zouenv) zou@HOSTNAME:/opt/kitsu$ cd ../zou/zouenv/
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ DB_PASSWORD=<PWD> /opt/zou/zouenv/bin/zou stamp-db
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ DB_PASSWORD=<PWD> /opt/zou/zouenv/bin/zou migrate-db
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
/opt/zou/zouenv/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py:1219: SAWarning: Cannot correctly sort tables; there are unresolvable cycles between tables "asset_instance, entity, output_file, preview_file, task, working_file", which is usually caused by mutually dependent foreign key constraints.  Foreign key constraints involving these tables will not be considered; this warning may raise an error in a future release.
  % (", ".join(sorted(t.fullname for t in err.cycles)),)
INFO  [alembic.autogenerate.compare] Detected added column 'entity.nb_entities_out'
INFO  [alembic.autogenerate.compare] Detected added column 'entity.ready_for'
INFO  [alembic.autogenerate.compare] Detected added foreign key (ready_for)(id) on table entity
INFO  [alembic.autogenerate.compare] Detected added column 'notification.reply_id'
INFO  [alembic.autogenerate.compare] Detected changed unique constraint 'notification_uc' on 'notification': columns ('author_id', 'comment_id', 'person_id', 'type') to ('author_id', 'comment_id', 'person_id', 'reply_id', 'type')
INFO  [alembic.autogenerate.compare] Detected added index 'ix_notification_reply_id' on '['reply_id']'
INFO  [alembic.autogenerate.compare] Detected added column 'preview_file.validation_status'
INFO  [alembic.autogenerate.compare] Detected added column 'task.nb_assets_ready'
  Generating /opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/versions/56b50e9962c5_.py ...  done
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 7b1f765677d8 -> 56b50e9962c5, empty message
Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/cli.py", line 76, in upgrade_db
    flask_migrate.upgrade(directory=directory)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/env.py", line 114, in <module>
    run_migrations_online()
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/env.py", line 91, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/alembic/runtime/migration.py", line 560, in run_migrations
    step.migration_fn(**kw)
  File "/opt/zou/zouenv/lib/python3.6/site-packages/zou/migrations/versions/56b50e9962c5_.py", line 30, in upgrade
    op.add_column('preview_file', sa.Column('validation_status', sqlalchemy_utils.types.choice.ChoiceType(length=255), nullable=True))
TypeError: __init__() got an unexpected keyword argument 'length'
```

So i've got also errors after starting **zou** service in logs, and the **kitsu** web page is stuck!
```
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ systemctl start {zou,zou-events.service}
```

But the solution I've found was to edit the last migration file.

As it's mentionned in the migration file **"commands auto generated by Alembic - please adjust!"**:

```
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ systemctl stop {zou,zou-events.service}
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ vim `python -c "import site; print(site.getsitepackages()[0])"`/zou/migrations/versions/56b50e9962c5_.py
```
adding/ replacing:
```
# Add
from zou.app.models.preview_file import VALIDATION_STATUSES

# Replace
    op.add_column('preview_file', sa.Column('validation_status', sqlalchemy_utils.types.choice.ChoiceType(VALIDATION_STATUSES), nullable=True))
```
Then re-upgrade
```
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ DB_PASSWORD=<PWD> /opt/zou/zouenv/bin/zou upgrade-db
(zouenv) zou@HOSTNAME:/opt/zou/zouenv$ systemctl start {zou,zou-events.service}
```

Then all is back to normal! And I'm on the last master branch, before next official release.

**Comment by frankrousseau** [comment]
Yes, the problem is that you made a Pull Request on the master branch without having an up-to-date list of migrations. So, I had to modify your database revision to apply it after our last change instead of the one you set. That's why it has put some mess in your codebase. 

I think the best way was to mark the last alembic revision applied in the database to the changes that occurred prior to the mattermost revision. Then, comment the lines that added the mattermost fields, in the revision file from our master branch. Then run the migration. It's a little bit hacky but that way you are sure that you have the right revision from the master branch applied to your database.
