### ISSUE TITLE
This preview is broken

### ISSUE THREAD

**Issue by coolturens** [cgwire/zou#428]
Hello, I have this issue, I tried aixzhou0216 solution from the #353 but still not working. I can see .jpg but not video.

this is the gunicorn.log

[2022-02-22 09:54:00,300] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/files/previews/424/747/42474714-d865-42bc-b13d-39c4f46596e2'
[2022-02-22 09:54:00,300] ERROR in resources: Non-movie file was not found for: 42474714-d865-42bc-b13d-39c4f46596e2
[2022-02-22 09:56:44,936] ERROR in preview_files_service: b"ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)\n  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 31.100 / 56. 31.100\n  libavcodec     58. 54.100 / 58. 54.100\n  libavformat    58. 29.100 / 58. 29.100\n  libavdevice    58.  8.100 / 58.  8.100\n  libavfilter     7. 57.100 /  7. 57.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  5.100 /  5.  5.100\n  libswresample   3.  5.100 /  3.  5.100\n  libpostproc    55.  5.100 / 55.  5.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from '/opt/zou/tmp/3f0d9edd-b783-450a-bf15-608fe557d344.mp4.tmp':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    date            : 2022/02/22 03:56:17\n    encoder         : Lavf58.76.100\n  Duration: 00:00:02.52, start: 0.000000, bitrate: 261 kb/s\n    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 960x540 [SAR 1:1 DAR 16:9], 252 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\n    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s (default)\n    Metadata:\n      handler_name    : SoundHandler\nPlease use -b:a or -b:v, -b is ambiguous\nStream mapping:\n  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))\n  Stream #0:1 -> #0:1 (aac (native) -> aac (native))\nPress [q] to stop, [?] for help\n[libx264 @ 0x55d0787593c0] using SAR=1/1\n[libx264 @ 0x55d0787593c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2\n[libx264 @ 0x55d0787593c0] profile High, level 5.0\n[libx264 @ 0x55d0787593c0] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=abr mbtree=1 bitrate=28000 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00\nOutput #0, mp4, to '/opt/zou/tmp/3f0d9edd-b783-450a-bf15-608fe557d344.mp4':\n  Metadata:\n    major_brand     : isom\n    minor_version   : 512\n    compatible_brands: isomiso2avc1mp41\n    date            : 2022/02/22 03:56:17\n    encoder         : Lavf58.29.100\n    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 28000 kb/s, 24 fps, 12288 tbn, 24 tbc (default)\n    Metadata:\n      handler_name    : VideoHandler\n      encoder         : Lavc58.54.100 libx264\n    Side data:\n      cpb: bitrate max/min/avg: 0/0/28000000 buffer size: 0 vbv_delay: -1\n    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)\n    Metadata:\n      handler_name    : SoundHandler\n      encoder         : Lavc58.54.100 aac\nframe=   45 fps=0.0 q=0.0 size=       0kB time=00:00:01.81 bitrate=   0.2kbits/s speed=3.55x    \rframe=   50 fps= 42 q=0.0 size=       0kB time=00:00:02.02 bitrate=   0.2kbits/s speed=1.69x    \rframe=   51 fps= 29 q=0.0 size=       0kB time=00:00:02.09 bitrate=   0.2kbits/s speed=1.19x    \r"
[2022-02-22 09:56:44,939] ERROR in preview_files_service: failed
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/app/services/preview_files_service.py", line 148, in prepare_and_store_movie
    ) = movie.normalize_movie(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/utils/movie.py", line 144, in normalize_movie
    raise (e)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/utils/movie.py", line 141, in normalize_movie
    stream.run(quiet=False, capture_stderr=True, overwrite_output=True)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
[2022-02-22 09:56:45,301] ERROR in resources: [Errno 2] No such file or directory: '/opt/zou/previews/files/previews/3f0/d9e/3f0d9edd-b783-450a-bf15-608fe557d344'
[2022-02-22 09:56:45,301] ERROR in resources: Non-movie file was not found for: 3f0d9edd-b783-450a-bf15-608fe557d344

thanks!

**Comment by frankrousseau** [comment]
Hello, thank you for reporting this bug. If you can provide the video, it would help us to fix the problem or to propose a solution.

**Comment by coolturens** [comment]
Yes of course, here is the video, it is a simple testing shot for it

https://drive.google.com/file/d/1X4XK1R_hhQl7hfHurqaHyyDIxmV1onHn/view?usp=sharing

**Comment by coolturens** [comment]
A couple of screenshots, maybe it help.

![Captura de pantalla 2022-02-22 162519](https://user-images.githubusercontent.com/2522570/155230178-13bbf333-a5de-4929-a68b-cf92942f6a71.png)
![Captura de pantalla 2022-02-22 162203](https://user-images.githubusercontent.com/2522570/155230190-753c4b8d-c4ff-434d-8bd2-883d1c68a54f.png)

**Comment by coolturens** [comment]
I fixed it increasing the memory ram and volume of the droplet O.O, sorry for the waste of time because my lack of knowledge on that.

**Comment by frankrousseau** [comment]
Great thank you! Yes ffmpeg consumes a lot of resources.
