### ISSUE TITLE
LDAP sync - sqlalchemy TimeoutError: QueuePool limit reached

### ISSUE THREAD

**Issue by Plyrolith** [cgwire/zou#459]
Hey,

I upgraded to version 0.14.0 and after running flawlessly for around 30 minutes, Zou/Kitsu completely freeze (the web browser only draws Kitsu's background color). After a few seconds, Kitsu will load the login screen, but authenticating is not possible.
We have a small team working on our instance, usually around 5-20 people at a time.

It seems to be that sqlalchemy's queue pool limit is reached and Zou doesn't close the database connections. (?)
I tested with various Zou versions, and the error persists starting from version 0.13.57 (0.13.55 definitely still works for us).

Our Zou instance is running in a docker container (python:3.7-alpine, Zou installed with pip) with a separate service each for events and job queue. Kitsu is in a container (nginx:alpine, Kitsu cloned from git) as well.

After Kitsu freezes, Zou throws the following error:

```log
zou-app      | [2022-04-28 16:32:23 +0000] [10] [ERROR] Error handling request //data/assets/with-tasks?project_id=02508655-9c35-46a4-8ebd-8bdfab5c7139
zou-app      | Traceback (most recent call last):
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 55, in handle
zou-app      |     self.handle_request(listener_name, req, client, addr)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
zou-app      |     super().handle_request(listener_name, req, sock, addr)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
zou-app      |     respiter = self.wsgi(environ, resp.start_response)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
zou-app      |     return self.wsgi_app(environ, start_response)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
zou-app      |     response = self.handle_exception(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   [Previous line repeated 17 more times]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
zou-app      |     reraise(exc_type, exc_value, tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
zou-app      |     raise value.with_traceback(tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
zou-app      |     response = self.full_dispatch_request()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
zou-app      |     rv = self.handle_user_exception(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   [Previous line repeated 17 more times]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
zou-app      |     reraise(exc_type, exc_value, tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
zou-app      |     raise value.with_traceback(tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
zou-app      |     rv = self.dispatch_request()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
zou-app      |     return self.view_functions[rule.endpoint](**req.view_args)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
zou-app      |     resp = resource(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
zou-app      |     return self.dispatch_request(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
zou-app      |     resp = meth(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
zou-app      |     return fn(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/blueprints/assets/resources.py", line 88, in get
zou-app      |     return assets_service.get_assets_and_tasks(criterions, page)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/services/assets_service.py", line 205, in get_assets_and_tasks
zou-app      |     ) in query.all():
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
zou-app      |     return list(self)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
zou-app      |     return self._execute_and_instances(context)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
zou-app      |     querycontext, self._connection_from_session, close_with_result=True
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
zou-app      |     mapper=self._bind_mapper(), clause=querycontext.statement, **kw
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
zou-app      |     conn = self.session.connection(**kw)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
zou-app      |     execution_options=execution_options,
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
zou-app      |     engine, execution_options
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
zou-app      |     conn = bind._contextual_connect()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
zou-app      |     self._wrap_pool_connect(self.pool.connect, None),
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
zou-app      |     return fn()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
zou-app      |     return _ConnectionFairy._checkout(self)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
zou-app      |     fairy = _ConnectionRecord.checkout(pool)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
zou-app      |     rec = pool._do_get()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
zou-app      |     code="3o7r",
zou-app      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 30 overflow 60 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
zou-app      | 192.168.80.4 - - [28/Apr/2022:16:32:23 +0000] "GET //data/assets/with-tasks?project_id=02508655-9c35-46a4-8ebd-8bdfab5c7139 HTTP/1.0" 500 0 "-" "-"
zou-app      | 192.168.80.4 - - [28/Apr/2022:16:32:23 +0000] "GET //config HTTP/1.0" 200 26 "https://***/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
zou-app      | 192.168.80.4 - - [28/Apr/2022:16:32:25 +0000] "POST //auth/login HTTP/1.0" 200 1357 "https://***/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
zou-app      | 192.168.80.4 - - [28/Apr/2022:16:32:28 +0000] "GET //config HTTP/1.0" 200 26 "https://***/productions/02508655-9c35-46a4-8ebd-8bdfab5c7139/assets?search=" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
zou-app      | 192.168.80.4 - - [28/Apr/2022:16:32:28 +0000] "GET //auth/authenticated HTTP/1.0" 200 1481 "https://***/productions/02508655-9c35-46a4-8ebd-8bdfab5c7139/assets?search=" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
zou-app      | [2022-04-28 16:32:33 +0000] [10] [ERROR] Error handling request //data/tasks/e4b2445b-45d3-42b3-8b99-8ef5c72bab13/comments
zou-app      | Traceback (most recent call last):
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 55, in handle
zou-app      |     self.handle_request(listener_name, req, client, addr)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
zou-app      |     super().handle_request(listener_name, req, sock, addr)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
zou-app      |     respiter = self.wsgi(environ, resp.start_response)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
zou-app      |     return self.wsgi_app(environ, start_response)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
zou-app      |     response = self.handle_exception(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   [Previous line repeated 17 more times]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
zou-app      |     reraise(exc_type, exc_value, tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
zou-app      |     raise value.with_traceback(tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
zou-app      |     response = self.full_dispatch_request()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
zou-app      |     rv = self.handle_user_exception(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   [Previous line repeated 17 more times]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
zou-app      |     reraise(exc_type, exc_value, tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
zou-app      |     raise value.with_traceback(tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
zou-app      |     rv = self.dispatch_request()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
zou-app      |     return self.view_functions[rule.endpoint](**req.view_args)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
zou-app      |     resp = resource(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
zou-app      |     return self.dispatch_request(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
zou-app      |     resp = meth(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
zou-app      |     return fn(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/blueprints/tasks/resources.py", line 105, in get
zou-app      |     return tasks_service.get_comments(task_id, is_client, is_manager)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/services/tasks_service.py", line 502, in get_comments
zou-app      |     (comments, comment_ids) = _run_task_comments_query(query)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/services/tasks_service.py", line 553, in _run_task_comments_query
zou-app      |     for result in query.all():
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
zou-app      |     return list(self)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
zou-app      |     return self._execute_and_instances(context)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
zou-app      |     querycontext, self._connection_from_session, close_with_result=True
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
zou-app      |     mapper=self._bind_mapper(), clause=querycontext.statement, **kw
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
zou-app      |     conn = self.session.connection(**kw)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
zou-app      |     execution_options=execution_options,
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
zou-app      |     engine, execution_options
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
zou-app      |     conn = bind._contextual_connect()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
zou-app      |     self._wrap_pool_connect(self.pool.connect, None),
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
zou-app      |     return fn()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
zou-app      |     return _ConnectionFairy._checkout(self)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
zou-app      |     fairy = _ConnectionRecord.checkout(pool)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
zou-app      |     rec = pool._do_get()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
zou-app      |     code="3o7r",
zou-app      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 30 overflow 60 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
zou-app      | 192.168.80.4 - - [28/Apr/2022:16:32:33 +0000] "GET //data/tasks/e4b2445b-45d3-42b3-8b99-8ef5c72bab13/comments HTTP/1.0" 500 0 "-" "-"

```

After the timeout is over, we also this error (and authentication is not possible):
`ERROR in resources: Identity loading timed out`

Thanks,
-Tristan

**Comment by frankrousseau** [comment]
Hello,
You can try to increase these values via environment variables: https://github.com/cgwire/zou/blob/master/zou/app/config.py#L45-L48

**Comment by Plyrolith** [comment]
I just figured out the source:
Our LDAP user sync runs every 30 minutes!
I manually synchronized using `zou sync-with-ldap-server`  and it immediately created overload.

# The problem is LDAP sync

**Comment by Plyrolith** [comment]
Whenever I edit a person, I'm getting the following error:

```
zou-app      | 172.18.0.7 - - [10/May/2022:17:54:56 +0000] "GET //data/persons/621b5743-56e8-4eff-b316-b8a58f0b9be0 HTTP/1.0" 200 809 "https://xxx.xx/productions/02508655-9c35-46a4-8ebd-8bdfab5c7139/asset/tasks/ebb20bb5-f6de-4d3c-a55e-25fb0f79b8b4/previews/8a8be1ee-b3cd-4931-a8e7-efaeef50be21" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
zou-app      | [2022-05-10 17:54:56 +0000] [8] [ERROR] Error handling request //data/persons/621b5743-56e8-4eff-b316-b8a58f0b9be0
zou-app      | Traceback (most recent call last):
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 55, in handle
zou-app      |     self.handle_request(listener_name, req, client, addr)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
zou-app      |     super().handle_request(listener_name, req, sock, addr)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
zou-app      |     respiter = self.wsgi(environ, resp.start_response)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
zou-app      |     return self.wsgi_app(environ, start_response)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
zou-app      |     response = self.handle_exception(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   [Previous line repeated 17 more times]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
zou-app      |     reraise(exc_type, exc_value, tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
zou-app      |     raise value.with_traceback(tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
zou-app      |     response = self.full_dispatch_request()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
zou-app      |     rv = self.handle_user_exception(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   [Previous line repeated 17 more times]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
zou-app      |     reraise(exc_type, exc_value, tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
zou-app      |     raise value.with_traceback(tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
zou-app      |     rv = self.dispatch_request()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
zou-app      |     return self.view_functions[rule.endpoint](**req.view_args)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
zou-app      |     resp = resource(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
zou-app      |     return self.dispatch_request(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
zou-app      |     resp = meth(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
zou-app      |     return fn(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/blueprints/crud/base.py", line 264, in get
zou-app      |     result = self.serialize_instance(instance)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/blueprints/crud/person.py", line 82, in serialize_instance
zou-app      |     return instance.present_minimal()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/models/person.py", line 88, in present_minimal
zou-app      |     "departments": data["departments"],
zou-app      | KeyError: 'departments'
```

Maybe the exception leads to an abandoned, unclosed database connection?

**Comment by Plyrolith** [comment]
Fix #472  tested & confirmed! Thanks!

**Comment by frankrousseau** [comment]
Please keep it open, the overload problem is still there. I know how to fix this, but it will require some time to do it.

**Comment by frankrousseau** [comment]
@Plyrolith can you tell me how you plotted the PG connection graph?

**Comment by Plyrolith** [comment]
Hey Frank! Our main database is an AWS RDS instance, which provides monitoring tools (where I captured the graph). Another tool we use is pgAdmin (https://www.pgadmin.org/).
pgAdmin also comes with a dashboard that includes a simple connections graph:

![image](https://user-images.githubusercontent.com/49444317/184601549-c001e7bb-efbb-498b-aec5-ae6f8d8afb2c.png)

I also want to state again that since #474 we haven't had any issues.

Hope that helps!
-Tristan

**Comment by frankrousseau** [comment]
Ok great, so let's close this issue. And thank you for the tips!

**Comment by Plyrolith** [comment]
@frankrousseau 
I just tried updating to 0.15.4 and the error is back... this time for workers it seems.

All versions before 0.14.17 seem to work fine; could not determine which commit is responsible since then.

```python
zou-app      | [2022-09-01 08:17:15 +0000] [7] [ERROR] Error handling request //data/projects/02508655-9c35-46a4-8ebd-8bdfab5c7139/milestones
zou-app      | Traceback (most recent call last):
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 55, in handle
zou-app      |     self.handle_request(listener_name, req, client, addr)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
zou-app      |     super().handle_request(listener_name, req, sock, addr)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 106, in handle_request
zou-app      |     respiter = self.wsgi(environ, resp.start_response)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
zou-app      |     return self.wsgi_app(environ, start_response)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
zou-app      |     response = self.handle_exception(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   [Previous line repeated 18 more times]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
zou-app      |     reraise(exc_type, exc_value, tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
zou-app      |     raise value.with_traceback(tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
zou-app      |     response = self.full_dispatch_request()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
zou-app      |     rv = self.handle_user_exception(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
zou-app      |     return original_handler(e)
zou-app      |   [Previous line repeated 18 more times]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
zou-app      |     reraise(exc_type, exc_value, tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
zou-app      |     raise value.with_traceback(tb)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
zou-app      |     rv = self.dispatch_request()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
zou-app      |     return self.view_functions[rule.endpoint](**req.view_args)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
zou-app      |     resp = resource(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
zou-app      |     return self.dispatch_request(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
zou-app      |     resp = meth(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
zou-app      |     return fn(*args, **kwargs)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/blueprints/projects/resources.py", line 760, in get
zou-app      |     return schedule_service.get_milestones_for_project(project_id)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/zou/app/services/schedule_service.py", line 201, in get_milestones_for_project
zou-app      |     return [milestone.present() for milestone in query.all()]
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
zou-app      |     return list(self)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
zou-app      |     return self._execute_and_instances(context)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
zou-app      |     querycontext, self._connection_from_session, close_with_result=True
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
zou-app      |     mapper=self._bind_mapper(), clause=querycontext.statement, **kw
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
zou-app      |     conn = self.session.connection(**kw)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
zou-app      |     execution_options=execution_options,
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
zou-app      |     engine, execution_options
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
zou-app      |     conn = bind._contextual_connect()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
zou-app      |     self._wrap_pool_connect(self.pool.connect, None),
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
zou-app      |     return fn()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
zou-app      |     return _ConnectionFairy._checkout(self)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
zou-app      |     fairy = _ConnectionRecord.checkout(pool)
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
zou-app      |     rec = pool._do_get()
zou-app      |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
zou-app      |     code="3o7r",
zou-app      | sqlalchemy.exc.TimeoutError: QueuePool limit of size 30 overflow 30 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
zou-app      | 172.18.0.7 - - [01/Sep/2022:08:17:13 +0000] "GET //pictures/thumbnails/projects/02508655-9c35-46a4-8ebd-8bdfab5c7139.png HTTP/1.0" 500 0 "-" "-"
```

**Comment by frankrousseau** [comment]
@EvanBldy, I think we should rewrite this function without database committing each change directly. We should add the changes to the db session and commit them at the end of the function.
