### ISSUE TITLE
Valueerror while init-db

### ISSUE THREAD

**Issue by sushant36000** [cgwire/zou#463]
Creating database and tables...
Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/cli.py", line 29, in init_db
    flask_migrate.upgrade(directory=directory)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/opt/zou/zouenv/lib/python3.8/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/zou/zouenv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/zou/zouenv/lib/python3.8/site-packages/zou/migrations/env.py", line 25, in <module>
    config.set_main_option(
  File "/opt/zou/zouenv/lib/python3.8/site-packages/alembic/config.py", line 248, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/opt/zou/zouenv/lib/python3.8/site-packages/alembic/config.py", line 275, in set_section_option
    self.file_config.set(section, name, value)
  File "/usr/lib/python3.8/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.8/configparser.py", line 894, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/lib/python3.8/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'postgresql://postgres:Sushant%40304@localhost:5432/zoudb' at position 29

And I am using ubuntu 20.04.4

**Comment by frankrousseau** [comment]
Make sure that the database is up and running and the user was properly created. Your password seems to use some special chars that is not supported to set up the postgres url.

**Comment by sushant36000** [comment]
> Make sure that the database is up and running and the user was properly created. Your password seems to use some special chars that is not supported to set up the postgres URL.


Thanks a lot
I rechecked and in postgres I was using special chars in password that's why I was getting such errors. Thanks a lot.
