### ISSUE TITLE
Can not log on to restored database.

### ISSUE THREAD

**Issue by flinfo** [cgwire/zou#524]
I can successfully backup and restore the Zou db from one server to another.
I seem to be unable to log in as any of the users in the database though. Is this a bug or am I missing a step?

old server: {"name": "Zou", "version": "0.13.27", "database-up": true, "key-value-store-up": true, "event-stream-up": true, "job-queue-up": false}
new server: {"name": "Zou", "version": "0.15.6", "database-up": true, "key-value-store-up": true, "event-stream-up": true, "job-queue-up": false}

On new server:
```
createdb -h localhost -p 5432 -U postgres zoudbxx
pg_restore -h localhost -p 5432 -U postgres -d zoudbxx 2022-09-20-09-zou-db-backup.sql
```

```
psql -U postgres
\l+
```
returns 
```
...
zoudbxx   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |                       | 71 MB   | pg_default |
...
```

**note this is now 71MB

```
\c zoudbxx
You are now connected to database "zoudb13" as user "postgres"

TABLE person;
```
correctly lists all users from the database, including name@company.com (using as an example)

update /etc/systemd/system/zou.service to use new database
restart server

After server restarted, when I try to log in to Kitsu page: "Log in failed, please verify your credentials"

```
cd /opt/zou
. zouenv/bin/activate
sudo -u zou DB_PASSWORD=xxxxxxxx DB_DATABASE=zoudbxx /opt/zou/zouenv/bin/zou set-default-password name@company.com
```
returns:
```
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column person.archived does not exist
LINE 2: ... AS person_phone, person.active AS person_active, person.arc...
                                                             ^
HINT:  Perhaps you meant to reference the column "person.active".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/cli.py", line 180, in set_default_password
    persons_service.update_password(email, password)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/persons_service.py", line 218, in update_password
    person = get_person_by_email_raw(email)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/persons_service.py", line 119, in get_person_by_email_raw
    person = Person.get_by(email=email)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/models/base.py", line 48, in get_by
    return cls.query.filter_by(**kw).first()
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column person.archived does not exist
LINE 2: ... AS person_phone, person.active AS person_active, person.arc...
                                                             ^
HINT:  Perhaps you meant to reference the column "person.active".

[SQL: SELECT anon_1.person_id AS anon_1_person_id, anon_1.person_created_at AS anon_1_person_created_at, anon_1.person_updated_at AS anon_1_person_updated_at, anon_1.person_first_name AS anon_1_person_first_name, anon_1.person_last_name AS anon_1_person_last_name, anon_1.person_email AS anon_1_person_email, anon_1.person_phone AS anon_1_person_phone, anon_1.person_active AS anon_1_person_active, anon_1.person_archived AS anon_1_person_archived, anon_1.person_last_presence AS anon_1_person_last_presence, anon_1.person_password AS anon_1_person_password, anon_1.person_desktop_login AS anon_1_person_desktop_login, anon_1.person_shotgun_id AS anon_1_person_shotgun_id, anon_1.person_timezone AS anon_1_person_timezone, anon_1.person_locale AS anon_1_person_locale, anon_1.person_data AS anon_1_person_data, anon_1.person_role AS anon_1_person_role, anon_1.person_has_avatar AS anon_1_person_has_avatar, anon_1.person_notifications_enabled AS anon_1_person_notifications_enabled, anon_1.person_notifications_slack_enabled AS anon_1_person_notifications_slack_enabled, anon_1.person_notifications_slack_userid AS anon_1_person_notifications_slack_userid, anon_1.person_notifications_mattermost_enabled AS anon_1_person_notifications_mattermost_enabled, anon_1.person_notifications_mattermost_userid AS anon_1_person_notifications_mattermost_userid, anon_1.person_notifications_discord_enabled AS anon_1_person_notifications_discord_enabled, anon_1.person_notifications_discord_userid AS anon_1_person_notifications_discord_userid, department_1.id AS department_1_id, department_1.created_at AS department_1_created_at, department_1.updated_at AS department_1_updated_at, department_1.name AS department_1_name, department_1.color AS department_1_color
FROM (SELECT person.id AS person_id, person.created_at AS person_created_at, person.updated_at AS person_updated_at, person.first_name AS person_first_name, person.last_name AS person_last_name, person.email AS person_email, person.phone AS person_phone, person.active AS person_active, person.archived AS person_archived, person.last_presence AS person_last_presence, person.password AS person_password, person.desktop_login AS person_desktop_login, person.shotgun_id AS person_shotgun_id, person.timezone AS person_timezone, person.locale AS person_locale, person.data AS person_data, person.role AS person_role, person.has_avatar AS person_has_avatar, person.notifications_enabled AS person_notifications_enabled, person.notifications_slack_enabled AS person_notifications_slack_enabled, person.notifications_slack_userid AS person_notifications_slack_userid, person.notifications_mattermost_enabled AS person_notifications_mattermost_enabled, person.notifications_mattermost_userid AS person_notifications_mattermost_userid, person.notifications_discord_enabled AS person_notifications_discord_enabled, person.notifications_discord_userid AS person_notifications_discord_userid
FROM person
WHERE person.email = lower(%(lower_1)s)
 LIMIT %(param_1)s) AS anon_1 LEFT OUTER JOIN (department_link AS department_link_1 JOIN department AS department_1 ON department_1.id = department_link_1.department_id) ON anon_1.person_id = department_link_1.person_id]
[parameters: {'lower_1': 'name@company.com', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

OK, try create new user:
`sudo -u zou DB_PASSWORD=xx DB_DATABASE=zoudbxx /opt/zou/zouenv/bin/zou create-admin nametwo@company.com`
returns:
```
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "archived" of relation "person" does not exist
LINE 1: ..._at, first_name, last_name, email, phone, active, archived, ...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou/zouenv/bin/zou", line 8, in <module>
    sys.exit(cli())
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/cli.py", line 137, in create_admin
    persons_service.create_person(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/persons_service.py", line 198, in create_person
    person = Person.create(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/models/base.py", line 72, in create
    db.session.commit()
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2677, in _flush
    with util.safe_reraise():
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "archived" of relation "person" does not exist
LINE 1: ..._at, first_name, last_name, email, phone, active, archived, ...
                                                             ^

[SQL: INSERT INTO person (id, created_at, updated_at, first_name, last_name, email, phone, active, archived, last_presence, password, desktop_login, shotgun_id, timezone, locale, role, has_avatar, notifications_enabled, notifications_slack_enabled, notifications_slack_userid, notifications_mattermost_enabled, notifications_mattermost_userid, notifications_discord_enabled, notifications_discord_userid) VALUES (%(id)s, %(created_at)s, %(updated_at)s, %(first_name)s, %(last_name)s, %(email)s, %(phone)s, %(active)s, %(archived)s, %(last_presence)s, %(password)s, %(desktop_login)s, %(shotgun_id)s, %(timezone)s, %(locale)s, %(role)s, %(has_avatar)s, %(notifications_enabled)s, %(notifications_slack_enabled)s, %(notifications_slack_userid)s, %(notifications_mattermost_enabled)s, %(notifications_mattermost_userid)s, %(notifications_discord_enabled)s, %(notifications_discord_userid)s)]
[parameters: {'id': UUID('9de8b8f4-f8fe-49b9-a6f8-6176074d6e50'), 'created_at': datetime.datetime(2022, 9, 21, 3, 7, 10, 962002), 'updated_at': datetime.datetime(2022, 9, 21, 3, 7, 10, 962018), 'first_name': 'Super', 'last_name': 'Admin', 'email': 'nametwo@company.com', 'phone': '', 'active': True, 'archived': False, 'last_presence': None, 'password': <psycopg2.extensions.Binary object at 0x7f6c515a5b90>, 'desktop_login': '', 'shotgun_id': None, 'timezone': 'Europe/Paris', 'locale': 'en_US', 'role': 'admin', 'has_avatar': False, 'notifications_enabled': False, 'notifications_slack_enabled': False, 'notifications_slack_userid': '', 'notifications_mattermost_enabled': False, 'notifications_mattermost_userid': '', 'notifications_discord_enabled': False, 'notifications_discord_userid': ''}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```
I am stumped! Help.

**Comment by flinfo** [comment]
Success... related to this issue (531):
https://github.com/cgwire/zou/issues/531
