### ISSUE TITLE
Problem when build movie in playlist

### ISSUE THREAD

**Issue by dinhthang1987** [cgwire/zou#551]
After update zou to new version 0.15.13, i have problem when build movie in playlist
```
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/playlists_service.py", line 536, in build_playlist_movie_file
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     current_app.logger.error(exc)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/werkzeug/local.py", line 348, in __getattr__
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     return getattr(self._get_current_object(), name)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/werkzeug/local.py", line 307, in _get_current_object
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     return self.__local()
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/flask/globals.py", line 52, in _find_app
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     raise RuntimeError(_app_ctx_err_msg)
Nov 30 15:14:18 vnsgnskitsu rq[49432]: RuntimeError: Working outside of application context.
Nov 30 15:14:18 vnsgnskitsu rq[49432]: This typically means that you attempted to use functionality that needed
Nov 30 15:14:18 vnsgnskitsu rq[49432]: to interface with the current application object in some way. To solve
Nov 30 15:14:18 vnsgnskitsu rq[49432]: this, set up an application context with app.app_context().  See the
Nov 30 15:14:18 vnsgnskitsu rq[49432]: documentation for more information.
Nov 30 15:14:18 vnsgnskitsu rq[49432]: Traceback (most recent call last):
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/playlists_service.py", line 498, in build_playlist_movie_file
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     tmp_file_paths = retrieve_playlist_tmp_files(previews)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/playlists_service.py", line 430, in retrieve_playlist_tmp_files
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     tmp_file_path, file_name = retrieve_playlist_tmp_file(preview_file)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/playlists_service.py", line 453, in retrieve_playlist_tmp_file
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     file_path = get_path_func(prefix, preview_file["id"])
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/stores/file_store.py", line 232, in get_local_movie_path
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     return path(movies, make_key(prefix, id))
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/stores/file_store.py", line 28, in path
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     self.root, folder_one, folder_two, folder_three, file_name
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/werkzeug/utils.py", line 91, in __get__
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     value = self.func(obj)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/flask_fs/storage.py", line 129, in root
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     return self.backend.root
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/werkzeug/utils.py", line 91, in __get__
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     value = self.func(obj)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/flask_fs/backends/local.py", line 48, in root
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     return self.config.get('root') or os.path.join(self.default_root, self.name)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/werkzeug/utils.py", line 91, in __get__
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     value = self.func(obj)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/flask_fs/backends/local.py", line 52, in default_root
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     default_root = current_app.config.get('FS_ROOT')
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/werkzeug/local.py", line 348, in __getattr__
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     return getattr(self._get_current_object(), name)
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/werkzeug/local.py", line 307, in _get_current_object
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     return self.__local()
Nov 30 15:14:18 vnsgnskitsu rq[49432]:   File "/opt/zou/zouenv/lib/python3.10/site-packages/flask/globals.py", line 52, in _find_app
Nov 30 15:14:18 vnsgnskitsu rq[49432]:     raise RuntimeError(_app_ctx_err_msg)
Nov 30 15:14:18 vnsgnskitsu rq[49432]: RuntimeError: Working outside of application context.
Nov 30 15:14:18 vnsgnskitsu rq[49432]: This typically means that you attempted to use functionality that needed
Nov 30 15:14:18 vnsgnskitsu rq[49432]: to interface with the current application object in some way. To solve
Nov 30 15:14:18 vnsgnskitsu rq[49432]: this, set up an application context with app.app_context().  See the
Nov 30 15:14:18 vnsgnskitsu rq[49432]: documentation for more information.
```

**Comment by frankrousseau** [comment]
Thank you for reporting. It will be fixed in the next release.
