### ISSUE TITLE
Updating a comment fails when persons are mentioned in the comment with @

### ISSUE THREAD

**Issue by tetsuoanimation** [cgwire/zou#557]
I am using gazu in this example but it seems the error is from zou:

When trying to update a comment with a text that includes a mention of another person the erver will fail adding the comment. It will fail the same way as if the user was trying to edit another users comment ( The returned message here is a bit unclear )

Trying to 'mention' someone that does not exist in the data base with @Some Name does not create this error.

Minimal reproducible example:
Create a comment and mention someone in the team. Then use gazu to try and edit that comment like so:

```comment = gazu.task.get_comment(comment_id)
gazu.task.update_comment(comment)```

Expected result: Comment is edited.
What happens: Server returns a Server error and the task is not edited

Local traceback for reference:
```
Traceback (most recent call last):
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/zou/app/blueprints/crud/base.py", line 394, in put
    self.instance.update(data)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/zou/app/models/base.py", line 193, in update
    setattr(self, key, value)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 272, in __set__
    self.impl.set(
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1334, in set
    collections.bulk_replace(
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/collections.py", line 801, in bulk_replace
    appender(member, _sa_initiator=initiator)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/collections.py", line 1116, in append
    item = __set(self, item, _sa_initiator)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/collections.py", line 1081, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/collections.py", line 717, in fire_append_event
    return self.attr.fire_append_event(
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1176, in fire_append_event
    value = fn(state, value, initiator or self._append_token)
  File "/tetsuo/pipeline/cgwire/zou/zouenv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 45, in append
    item_state = attributes.instance_state(item)
AttributeError: 'str' object has no attribute '_sa_instance_state'
```

**Comment by EvanBldy** [comment]
Hi @tetsuoanimation, I have made a fix for that (and every issues like that) in this PR : https://github.com/cgwire/zou/pull/780. 
Can you close if it's okay for you ? 
Thanks

**Comment by EvanBldy** [comment]
I will make a Zou release with this PR tonight
