### ISSUE TITLE
Can't create any task status

### ISSUE THREAD

**Issue by storyboat** [cgwire/zou#615]
Hi! Thanks for developing this great software!
We are using Kitsu for few moths now and we've came across with some issues with adding new stuff.

Every possible combination of full name and short name of task status gives me same error.
"An error occurred while saving this task status. Are you sure there is no task status with similar name?"

Error log:
`[2023-03-06 09:42:24,391] ERROR in base: 'is_default' is an invalid keyword argument for TaskStatus
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.9/site-packages/zou/app/blueprints/crud/base.py", line 188, in post
    instance = self.model.create(**data)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/zou/app/models/base.py", line 69, in create
    instance = cls(**kw)
  File "<string>", line 4, in __init__
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/base.py", line 839, in _declarative_constructor
    raise TypeError(
TypeError: 'is_default' is an invalid keyword argument for TaskStatus
`

Version: Kitsu 0.15.49
Maybe one of updates of Kitsu has break it up?

**Comment by frankrousseau** [comment]
Hello storyboat, did you update the database?

**Comment by storyboat** [comment]
No, should I do exactly that? https://zou.cg-wire.com/development/#update-database

**Comment by storyboat** [comment]
Okay, so my problem was trivial, I have updated Kitsu without updating Zou... 
After running [those steps](https://zou.cg-wire.com/#update) most of my problems vanished. Yay!

Still fighting with deleting one tysk type, getting an error:
> An error occurred while deleting this task type. There are probably data linked to it. Are you sure this task type has no task linked to it?

I can't any reference for it in the project.

`Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: update or delete on table "task_type" violates foreign key constraint "schedule_item_task_type_id_fkey" on table "schedule_item"
DETAIL:  Key (id)=(12dffdc8-6ced-4190-8823-fbb4833b4712) is still referenced from table "schedule_item".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.9/site-packages/zou/app/blueprints/crud/base.py", line 446, in delete
    instance.delete()
  File "/opt/zou/zouenv/lib/python3.9/site-packages/zou/app/models/base.py", line 187, in delete
    db.session.commit()
  File "<string>", line 2, in commit
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
    self._flush(objects)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3584, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
    flush_context.execute()
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 667, in execute
    util.preloaded.orm_persistence.delete_obj(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 343, in delete_obj
    _emit_delete_statements(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1468, in _emit_delete_statements
    c = connection._execute_20(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/zou/zouenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) update or delete on table "task_type" violates foreign key constraint "schedule_item_task_type_id_fkey" on table "schedule_item"
DETAIL:  Key (id)=(12dffdc8-6ced-4190-8823-fbb4833b4712) is still referenced from table "schedule_item".

[SQL: DELETE FROM task_type WHERE task_type.id = %(id)s]
[parameters: {'id': UUID('12dffdc8-6ced-4190-8823-fbb4833b4712')}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
`

**Comment by EvanBldy** [comment]
If you want to delete a task type you need to delete this task type from every projects (and every tasks using this task type)
