### ISSUE TITLE
Issue generating api key for bot with expiration date

### ISSUE THREAD

**Issue by MadsHangaard** [cgwire/zou#799]
**Context**

Studio name: Mint Copenhagen
Zou version: 0.19.25
Zou installation type: self-hosted on VirtualBox running Ubuntu Server 22.04.4 LTS 

**Describe the bug**
When trying to generate an API key for a bot with an expiration date, it fails with this error displayed in /opt/zou/logs/gunicorn_error.log

`[2024-04-19 15:10:56,557] ERROR in base: can't subtract offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/blueprints/crud/base.py", line 412, in put
    self.post_update(instance-dict, data)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/blueprints/crud/person.py", line 227, in post_update
    persons_service.create_access_token_for_raw_person(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/persons_service.py", line 560, in create_access_token_for_raw_person
    datetime.datetime.combine(
TypeError: can't subtract offset-naive and offset-aware datetimes`

**Expected behavior**
The API key should be generated successfully.

**Comment by EvanBldy** [comment]
Hi @MadsHangaard,
Thanks for the report ! 
I fixed that in this PR https://github.com/cgwire/zou/pull/800 and I made a new release. 
I close this issue, I will let you reopen it if there is still a problem.

**Comment by MadsHangaard** [comment]
I have tested it on my side with no issues. 👍
