### ISSUE TITLE
Setting Frame Numbers from previews doesn't work

### ISSUE THREAD

**Issue by lukas-remis** [cgwire/zou#896]
**Context**

Studio name: Imaginary Pixels
Kitsu version: 0.19.73
Production type: VFX

Auto-setting frame numbers based on previews doesn't work when FPS is set to 23.976.

Kitsu shows this error:
There was an error while extracting the frame numbers from the task type previews. Please contact our support team

Zou error logs:

[2024-12-13 11:21:05,408] ERROR in __init__: Traceback (most recent call last):
  File "/opt/zou/zouenv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zou/zouenv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/zou/zouenv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/opt/zou/zouenv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/blueprints/shots/resources.py", line 1651, in post
    return shots_service.set_frames_from_task_type_preview_files(
  File "/opt/zou/zouenv/lib/python3.10/site-packages/zou/app/services/shots_service.py", line 1672, in set_frames_from_task_type_preview_files
    nb_frames = round(preview_duration * int(project["fps"]))
ValueError: invalid literal for int() with base 10: '23.976'

 - OS: Ubuntu
 - Browser: Chrome, Opera

**Comment by NicoPennec** [comment]
Thank you for the report @lukas-remis 
It is an issue on the API side; I moved your issue to the right repository.

Zou seems to expect an integer value: https://github.com/cgwire/zou/blob/main/zou/app/services/shots_service.py#L1666

**Comment by EvanBldy** [comment]
Hi @lukas-remis, 
In the next release it will be fixed.

**Comment by lukas-remis** [comment]
Thanks very much!
